name: "Ansible"

on:
  pull_request:

jobs:
  terraform:
    name: "Ansible Syntax and Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Ansible Syntax Check
        run: |
          pushd ansible
          ansible-playbook -i inventory site.yml --syntax-check
          popd

      - name: Ansible Lint
        run: |
          ansible-lint -v ansible/roles/app
